# Generated by Django 5.2.17 on 2026-09-06 16:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(db_index=True, max_length=100, unique=True)),
                ('value', models.TextField(blank=True)),
                ('group', models.CharField(choices=[('general', 'General'), ('contact', 'Contact'), ('social', 'Social')], default='general', max_length=10)),
            ],
            options={
                'ordering': ['group', 'key'],
            },
        ),
    ]
