# Generated by Django 5.2.17 on 2026-09-07 05:56

from django.db import migrations

def update_user_roles(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    for user in User.objects.all():
        if user.role == "admin":
            user.role = "SUPERADMIN"
        elif user.role in ["editor", "viewer", "SUB_ADMIN"]:
            # If already SUB_ADMIN it's fine, but just in case
            user.role = "SUB_ADMIN"
        else:
            user.role = "SUB_ADMIN"
        
        # Superadmins must also be marked as is_staff and is_superuser
        if user.role == "SUPERADMIN":
            user.is_staff = True
            user.is_superuser = True

        user.save(update_fields=["role", "is_staff", "is_superuser"])

class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role_auditlog'),
    ]

    operations = [
        migrations.RunPython(update_user_roles, migrations.RunPython.noop),
    ]
