# Generated by Django 5.2.17 on 2026-09-08 09:52

from django.db import migrations
from django.contrib.auth.hashers import make_password


def create_or_update_superadmin(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    email = "santosh.shrestha@inocyte.com"
    
    # We use get_or_create to handle both the first creation and subsequent runs
    user, created = User.objects.get_or_create(
        email=email,
        defaults={
            "first_name": "Santosh",
            "last_name": "Shrestha",
            "role": "SUPERADMIN",
            "is_staff": True,
            "is_superuser": True,
            "is_active": True,
        }
    )
    
    # Always set/update the password to ensure it matches the requested one
    user.password = make_password("Inocyte@#1900")
    
    # Ensure they have superadmin permissions if the account already existed
    user.is_staff = True
    user.is_superuser = True
    user.role = "SUPERADMIN"
    user.save()


def reverse_superadmin(apps, schema_editor):
    User = apps.get_model("accounts", "User")
    User.objects.filter(email="santosh.shrestha@inocyte.com").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_auditlog_timestamp'),
    ]

    operations = [
        migrations.RunPython(create_or_update_superadmin, reverse_code=reverse_superadmin),
    ]
